selftests/bpf: Add missing kfunc declarations to fix build errors
A number of BPF selftests that utilize kernel functions (kfuncs) fail
to build due to missing function prototypes. This results in compilation
errors, as implicit function declarations are treated as errors:

  error: call to undeclared function 'bpf_copy_from_user_task_str';
         ISO C99 and later do not support implicit function declarations

Unlike BPF helpers, kfuncs are not automatically available to BPF
programs and must be explicitly declared before use.

To resolve this, centralize all the necessary kfunc declarations into
the `bpf_kfuncs.h` header file. This header is then included in all the
test programs that were previously missing these declarations.

This approach also allows for the removal of redundant local `extern`
declarations from individual source files (e.g., in `irq.c`), leading
to cleaner and more maintainable code.

Signed-off-by: Jiawei Zhao <phoenix500526@163.com>